name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Install Swift
          run: |
           wget "https://swift.org/builds/swift-5.1.3-release/ubuntu1804/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-ubuntu18.04.tar.gz"
           tar -xzf swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
           mv swift-5.1.3-RELEASE-ubuntu18.04/ swift/
           apt install build-essential libatomic1 -y
           ./swift/usr/bin/swift build -c release
